# Generated by Django 5.1.3 on 2024-12-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['created_on'], 'verbose_name': 'Property Image'},
        ),
    ]
